### ISSUE TITLE
Add support for Netbox 3.6

### ISSUE THREAD

**Issue by candlerb** [FlxPeters/netbox-plugin-prometheus-sd#132]
In Netbox 3.6, "device_role" has been renamed to "role". This gives the following exception:

```
Internal Server Error: /api/plugins/prometheus-sd/devices/

ValueError at /api/plugins/prometheus-sd/devices/
'device_role' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().

Request Method: GET
Request URL: https://netbox.example.net/api/plugins/prometheus-sd/devices/?tag=prom_snmp&status=active
Django Version: 4.2.4
Python Executable: /opt/netbox/venv/bin/python3.8
Python Version: 3.8.10
Python Path: ['/opt/netbox/netbox', '/opt/netbox', '/opt/netbox/venv/bin', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/opt/netbox/venv/lib/python3.8/site-packages']
Server time: Thu, 31 Aug 2023 10:08:31 +0000
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'corsheaders',
 'debug_toolbar',
 'graphiql_debug_toolbar',
 'django_filters',
 'django_tables2',
 'django_prometheus',
 'graphene_django',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'core',
 'account',
 'circuits',
 'dcim',
 'ipam',
 'extras',
 'tenancy',
 'users',
 'utilities',
 'virtualization',
 'wireless',
 'django_rq',
 'drf_spectacular',
 'drf_spectacular_sidecar',
 'netbox_prometheus_sd.PrometheusSD']
Installed Middleware:
['graphiql_debug_toolbar.middleware.DebugToolbarMiddleware',
 'django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'netbox.middleware.RemoteUserMiddleware',
 'netbox.middleware.CoreMiddleware',
 'netbox.middleware.MaintenanceModeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware']


Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/api/viewsets/__init__.py", line 91, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/netbox/netbox/netbox/api/viewsets/mixins.py", line 95, in list
    return super().list(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 46, in list
    return Response(serializer.data)
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/opt/netbox/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1883, in _fetch_all
    self._prefetch_related_objects()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1273, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/db/models/query.py", line 2310, in prefetch_related_objects
    raise ValueError(

Exception Type: ValueError at /api/plugins/prometheus-sd/devices/
Exception Value: 'device_role' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().
Raised during: netbox_prometheus_sd.api.views.DeviceViewSet
Request information:
USER: admin

GET:
tag = 'prom_snmp'
status = 'active'

POST: No POST data

FILES: No FILES data
```

**Comment by samoz83** [comment]
@FlxPeters Will there be a release soon on pypi for 3.6 support?

**Comment by candlerb** [comment]
You can put this in `/opt/netbox/local_requirements.txt`:

```
git+https://github.com/FlxPeters/netbox-plugin-prometheus-sd@ff2b0245
```

or to install the latest always:

```
git+https://github.com/FlxPeters/netbox-plugin-prometheus-sd@main
```

**Comment by FlxPeters** [comment]
New release is on the way 🚀
